url: https://ryanwu4.github.io
baseurl: ""

# Site settings
title: Ryan Wu's Portfolio
email: rhw2125@columbia.edu
description: "The engineering portfolio of Ryan Wu"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ryan-wu40/
  - title: facebook
    url: https://www.facebook.com/ryan.wu.7712826/
  - title: github
    url: https://github.com/ryanwu4

# Postal address (add as many lines as necessary)
address:
  - line: 70-31 108th St, Apt 2D
  - line: Forest Hills, NY, 11375

# Build settings
markdown: kramdown
permalink: pretty